### ISSUE TITLE
Problems encountered during build

### ISSUE THREAD

**Issue by Edward-Elric233** [ZJUVAI/DRGraph#2]
When I ran build.sh, I initially ran into a problem saying "reference to 'real' is ambiguous.I encountered another problem after changing 'real' to 'float' in the file. The problem is:
./src/algorithm/kdtreeub_index.hpp:1192:7: require from here
I don't understand what this means. I hope I can get your help.

**Comment by Basasuya** [comment]
Can you describe the detail of the error before you change the file?
I think it due to different gcc version.

BTW, I will add a new branch to change 'real' to 'float' in these days, maybe can solve your problem.

**Comment by FelixCAAuer** [comment]
I had a similar problem, where the build said "reference to 'real' is ambiguous". In my case this was due to a parallel installation of boost (1.71 in my case). Deinstalling all versions of boost I could find and installing boost 1.58 resolved it for me.

**Comment by Edward-Elric233** [comment]
> I had a similar problem, where the build said "reference to 'real' is ambiguous". In my case this was due to a parallel installation of boost (1.71 in my case). Deinstalling all versions of boost I could find and installing boost 1.58 resolved it for me.

You can use the FIX_REAL_BUG branch, which was created by the developer to fix the bug.By using this branch, I've solved my problem, and I hope it's helpful for you too.
